### ISSUE TITLE
Jsfiddle changed and elements are not getting scrolled completely into view so Selenium is failing when it tries to click on things

### ISSUE THREAD

**Issue by GeorgianaDan** [IBXCODECAT/FPSShooterGameHost#3]
Jsfiddle is using a different resolution or what the cause is but elements are not getting scrolled completely into view so Selenium is failing when it tries to click on things.

**Comment by IBXCODECAT** [comment]
Thank you for the feedback. We already have a version out for windows and this was just a demo and is considered depricated. I forgot to archive this repository. Sorry about that :|
